### ISSUE TITLE
[FEATURE] Update the existing comment instead of adding a new one

### ISSUE THREAD

**Issue by benoitf** [redhat-actions/try-in-web-ide#13]
### Is your feature request related to a problem? Please describe.

When we update a branch with new commits, there is new trigger and a new comment
so we can have like tons of comments. Usually other actions just update their existing comment (like dependabot or codecov bots)
But the comment content is not changing

### Describe the solution you'd like

1. Either update the existing comment with new content but I'm not sure it's updated
2. Do not add a new comment if there is already one

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by dkwon17** [comment]
Fixed by #27
