### ISSUE TITLE
[FEATURE] CI check for running `npm run test`

### ISSUE THREAD

**Issue by dkwon17** [redhat-actions/try-in-web-ide#8]
### Is your feature request related to a problem? Please describe.
It would be great if there was a GitHub action job that would check that all tests run from `npm run test` pass

### Describe the solution you'd like

A new job can probably be added here: https://github.com/redhat-actions/try-in-web-ide/blob/main/.github/workflows/ci.yml

**Comment by ibuziuk** [comment]
@dkwon17 can we close this one ?
